import { readRegistry, registryCompliance } from "./registry-security.js";

const esc=(value:unknown)=>String(value??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]??c));

export async function renderMetaDashboard(projectRoot:string) {
  const registry=await readRegistry(projectRoot).catch(()=>({version:"unknown",skills:[],hash:""}));
  const compliance=registryCompliance(registry);
  const active=registry.skills.filter(s=>s.status==="ACTIVE").length;
  const quarantined=registry.skills.filter(s=>s.status==="QUARANTINED"||s.status==="BLOCKED").length;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KROM Meta Engineering</title><style>body{margin:0;background:#0b1220;color:#e5edf7;font:14px system-ui,sans-serif}main{max-width:1180px;margin:0 auto;padding:28px}.hero{display:flex;justify-content:space-between;gap:16px;align-items:end;border-bottom:1px solid #263449;padding-bottom:18px}.eyebrow{color:#6ee7b7;text-transform:uppercase;letter-spacing:.14em;font-size:11px}.muted{color:#9aabc0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px;margin:20px 0}.card{background:#111c2d;border:1px solid #263449;border-radius:12px;padding:16px}.value{font-size:28px;font-weight:800;margin-top:7px}.ok{color:#6ee7b7}.warn{color:#fbbf24}.bad{color:#fb7185}table{width:100%;border-collapse:collapse;background:#111c2d;border:1px solid #263449;border-radius:12px;overflow:hidden}th,td{text-align:left;padding:10px 12px;border-bottom:1px solid #263449}th{color:#9aabc0;font-size:12px}code{color:#bfdbfe}a{color:#93c5fd}</style></head><body><main><section class="hero"><div><div class="eyebrow">KROM META ENGINEERING SYSTEM</div><h1>Governed capability control center</h1><div class="muted">Observe → Plan → Patch → Test → Security Review → Release Gate → Verify → Rollback</div></div><div class="${compliance.status==="PASS"?"ok":"bad"}">${esc(compliance.status)}</div></section><section class="grid"><div class="card"><div class="muted">Registry version</div><div class="value">${esc(registry.version)}</div></div><div class="card"><div class="muted">Registered skills</div><div class="value">${active}/${registry.skills.length}</div></div><div class="card"><div class="muted">Quarantined / blocked</div><div class="value ${quarantined?"bad":"ok"}">${quarantined}</div></div><div class="card"><div class="muted">Autonomy default</div><div class="value">OBSERVE</div></div></section><section class="card"><h2>Registry evidence</h2><p class="muted">Hash: <code>${esc(registry.hash)}</code></p><table><thead><tr><th>Skill</th><th>Version</th><th>Owner</th><th>Status</th><th>Security</th></tr></thead><tbody>${registry.skills.slice(0,50).map(s=>`<tr><td>${esc(s.id)}</td><td>${esc(s.version)}</td><td>${esc(s.ownerDomain)}</td><td class="${s.status==="ACTIVE"?"ok":s.status==="BLOCKED"?"bad":"warn"}">${esc(s.status)}</td><td>${esc(s.securityLevel)}</td></tr>`).join("")}</tbody></table></section><p class="muted">Use MCP tools for creation, discovery, validation, security scan, repair planning, ledger, observability, drift, and release evidence. External skills are review-only until explicitly promoted.</p></main></body></html>`;
}
