import fs from "node:fs/promises";
import path from "node:path";
import { AutonomyMode, AuditOutcome, NormalizedAuditResult, RepairPlan, SecurityLevel } from "./types.js";

export const HIGH_RISK = new Set(["auth", "rls", "migration", "secrets", "credential", "billing", "delete", "production", "release", "security"]);
export function normalizeAudit(input:{invoked?:boolean;contractOk?:boolean;rawStatus?:string;expectedBlocked?:boolean;reason?:string;error?:boolean; evidence?:Record<string,unknown>}):NormalizedAuditResult { const invoked=input.invoked!==false; const contractOk=input.contractOk!==false; let outcomeClass:AuditOutcome="PASS"; if(input.error) outcomeClass="HARNESS_ERROR"; else if(!contractOk) outcomeClass="BLOCKED_UNEXPECTED"; else if(input.expectedBlocked) outcomeClass="BLOCKED_EXPECTED"; else if(input.rawStatus?.toUpperCase()==="UNAVAILABLE") outcomeClass="UNAVAILABLE_EXPECTED"; else if(input.rawStatus?.toUpperCase()==="BLOCKED") outcomeClass="BLOCKED_UNEXPECTED"; else if(!invoked) outcomeClass="REVIEW"; return {invoked,contractOk,outcomeClass,expectedForFixture:Boolean(input.expectedBlocked),rawStatus:input.rawStatus,redactedReason:input.reason?.slice(0,240),evidence:input.evidence}; }

export function repairPlan(input:{changeId:string;mode:AutonomyMode;findingConfidence:number;repairConfidence:number;securityImpact:SecurityLevel;filesAffected:string[];tests:string[];rollbackTarget?:string;task:string}):RepairPlan { const normalized=input.task.toLowerCase(); const highRisk=[...HIGH_RISK].some(k=>normalized.includes(k)); const blockers:string[]=[]; if(input.mode==="OBSERVE") blockers.push("OBSERVE mode permits detection only"); if(input.findingConfidence<0.8) blockers.push("finding confidence below 0.80"); if(input.repairConfidence<0.8) blockers.push("repair confidence below 0.80"); if(!input.filesAffected.length) blockers.push("no bounded files affected"); if(!input.tests.length) blockers.push("no regression tests supplied"); if(!input.rollbackTarget) blockers.push("rollback target is required"); if(highRisk||input.securityImpact==="high"||input.securityImpact==="critical") blockers.push("independent review required for high-risk change"); return {changeId:input.changeId,mode:input.mode,findingConfidence:input.findingConfidence,repairConfidence:input.repairConfidence,regressionRisk:highRisk?"HIGH":input.filesAffected.length>5?"MEDIUM":"LOW",securityImpact:input.securityImpact,filesAffected:input.filesAffected,tests:input.tests,rollbackTarget:input.rollbackTarget,allowed:blockers.length===0,blockers}; }

export async function appendLedger(root:string, entry:Record<string,unknown>) { const dir=path.join(root,".krom","meta"); await fs.mkdir(dir,{recursive:true}); const file=path.join(dir,"change-ledger.jsonl"); await fs.appendFile(file,JSON.stringify({...entry,timestamp:entry.timestamp??new Date().toISOString()})+"\n"); return file; }
export async function readLedger(root:string) { try { return (await fs.readFile(path.join(root,".krom","meta","change-ledger.jsonl"),"utf8")).trim().split("\n").filter(Boolean).map(x=>JSON.parse(x)); } catch { return []; } }
export function autonomyPolicy(mode:AutonomyMode) { return {mode,defaultMode:"OBSERVE",allowed:mode!=="OBSERVE"?"bounded planning and evidence only until gates pass":"detect and report only",highRiskRequiresReview:true,antiGaming:["cannot remove assertions","cannot skip failing tests","cannot disable security tools","cannot weaken release gates"],protectedAreas:["auth","RLS","migrations","secrets","audit","rollback","release"]}; }
export function catalogDrift(toolNames:string[]) { const seen=new Set<string>(); const duplicate:string[]=[]; const rows=toolNames.map(name=>{if(seen.has(name)) duplicate.push(name); seen.add(name); const m=name.match(/_v(\d+)$/); return {tool:name,domain:name.split("_")[0],currentVersion:m?`v${m[1]}`:"legacy",status:m?"VERSIONED":"REVIEW",deprecated:false,replacement:null,tests:"audit-covered"};}); return {status:duplicate.length?"REVIEW":"PASS",duplicates:[...new Set(duplicate)],rows}; }
export function observabilitySnapshot(input:{toolCalls:number;toolFailures:number;skillInvocations:number;blockedCalls:number;repairsProposed:number;repairsPassed:number;rollbackCount:number}) { const pct=(a:number,b:number)=>b?Math.round((a/b)*10000)/100:100; return {capturedAt:new Date().toISOString(),red:{rate:input.toolCalls,errors:input.toolFailures,duration:null},use:{utilization:null,saturation:null,errors:input.toolFailures},mcp:{calls:input.toolCalls,failures:input.toolFailures,blocked:input.blockedCalls},skills:{invocations:input.skillInvocations},selfHealing:{proposed:input.repairsProposed,passed:input.repairsPassed,successPercent:pct(input.repairsPassed,input.repairsProposed),rollbacks:input.rollbackCount},slo:{configured:false,note:"No thresholds invented; configure targets before enforcing SLOs"}}; }
export function releaseGate(gates:Array<{name:string;status:"PASS"|"BLOCKED"|"REVIEW";evidence?:unknown}>) { const blockers=gates.filter(g=>g.status==="BLOCKED"); const review=gates.filter(g=>g.status==="REVIEW"); return {decision:blockers.length?"BLOCKED":review.length?"REVIEW":"PASS",gates,blockers:blockers.map(g=>g.name),review:review.map(g=>g.name),failClosed:true}; }
