import * as z from "zod/v4";
import fs from "node:fs/promises";
import path from "node:path";
import { analyzeGap, canonicalSkillId, readRegistry, registryCompliance, safeSkillId, validateSkillPackage } from "./registry-security.js";
import { appendLedger, autonomyPolicy, catalogDrift, normalizeAudit, observabilitySnapshot, releaseGate, repairPlan } from "./governance.js";
import { AutonomyMode, SecurityLevel } from "./types.js";

type Deps={server:any;projectRoot:string;result:(text:string)=>any;errorResult:(e:unknown)=>any;toolNames:()=>string[]};
async function draftSkill(root:string,input:any){ if(!safeSkillId(input.name)) throw new Error("invalid canonical skill name"); const dir=path.join(root,".krom","meta","skill-drafts",input.name); await fs.mkdir(dir,{recursive:true}); const body=`---\nname: ${input.name}\ndescription: ${input.description}\n---\n\n# ${input.name}\n\n## Purpose\n${input.purpose}\n\n## Trigger conditions\n${input.triggers.map((x:string)=>`- ${x}`).join("\n")}\n\n## Responsibilities\n${input.responsibilities.map((x:string)=>`- ${x}`).join("\n")}\n\n## Security level\n${input.securityLevel}\n\n## Dependencies\n${input.dependencies.length?input.dependencies.map((x:string)=>`- ${x}`).join("\n"):"- None declared"}\n\n## Governance\nThis is a draft. Validate, security-scan, scenario-test, review, and register it before activation.\n`; await fs.writeFile(path.join(dir,"SKILL.md"),body); return {status:"DRAFT_CREATED",path:path.relative(root,dir),next:["skill_validate_v51","skill_security_scan_v51","skills_compliance_gate_v51"]}; }
async function discoverSkills(query:string){ const url=`https://api.github.com/search/repositories?q=${encodeURIComponent(query+" skill")}&per_page=10`; const response=await fetch(url,{headers:{accept:"application/vnd.github+json","user-agent":"krom-forge-skill-discovery"}}); if(!response.ok) return {status:"UNAVAILABLE_EXPECTED",httpStatus:response.status,source:"github-search",recommendation:"Do not import automatically; retry or use curated local sources."}; const data=await response.json() as any; return {status:"REVIEW",source:"github-search",query,results:(data.items??[]).map((item:any)=>({fullName:item.full_name,owner:item.owner?.login,description:item.description,stars:item.stargazers_count,updatedAt:item.updated_at,license:item.license?.spdx_id,url:item.html_url,installation:"NOT_PERFORMED"}))}; }
function compareVersions(left:string,right:string){ const parse=(v:string)=>v.replace(/^v/,'').split('.').map(x=>Number.parseInt(x,10)||0); const a=parse(left),b=parse(right); for(let i=0;i<3;i++) if(a[i]!==b[i]) return {relation:a[i]>b[i]?"NEWER":"OLDER",left,right}; return {relation:"EQUAL",left,right}; }

export function registerMetaEngineeringTools(d:Deps){ const {server,projectRoot,result,errorResult,toolNames}=d;
  server.registerTool("meta_registry_status_v51",{title:"Meta Registry Status v51",description:"Return the current versioned canonical skill registry, hashes, statuses, and compliance result.",inputSchema:z.object({}),annotations:{readOnlyHint:true,openWorldHint:false}},async()=>{try{const r=await readRegistry(projectRoot);return result(JSON.stringify({...r,compliance:registryCompliance(r)},null,2));}catch(e){return errorResult(e);}});
  server.registerTool("skill_create_v51",{title:"Skill Factory Draft v51",description:"Create a governed draft skill package under .krom/meta; never activates or installs a skill.",inputSchema:z.object({name:z.string().min(3),purpose:z.string().min(10),description:z.string().min(30),triggers:z.array(z.string()).min(1),responsibilities:z.array(z.string()).min(1),securityLevel:z.enum(["low","medium","high","critical"]),dependencies:z.array(z.string()).default([])}),annotations:{readOnlyHint:false,openWorldHint:false}},async(input:any)=>{try{return result(JSON.stringify(await draftSkill(projectRoot,input),null,2));}catch(e){return errorResult(e);}});
  server.registerTool("skill_validate_v51",{title:"Skill Validator v51",description:"Validate a local skill package for structure, frontmatter, references, scripts, secrets, URLs, traversal, and conflicts.",inputSchema:z.object({path:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:false}},async({path:skillPath}:any)=>{try{return result(JSON.stringify(await validateSkillPackage(projectRoot,skillPath),null,2));}catch(e){return errorResult(e);}});
  server.registerTool("skill_security_scan_v51",{title:"Skill Supply Chain Security v51",description:"Scan a skill package as untrusted code and classify secret, execution, URL, traversal, and encoded-payload findings.",inputSchema:z.object({path:z.string().min(1)}),annotations:{readOnlyHint:true,openWorldHint:false}},async({path:skillPath}:any)=>{try{const report=await validateSkillPackage(projectRoot,skillPath);return result(JSON.stringify({status:report.securityFindings.some(f=>["high","critical"].includes(f.severity))?"QUARANTINED":"REVIEW",findings:report.securityFindings,warnings:report.warnings},null,2));}catch(e){return errorResult(e);}});
  server.registerTool("skill_discover_v51",{title:"Skill Discovery & Curation v51",description:"Search trusted-source metadata for candidate skills; returns review candidates only and never installs or activates Internet content.",inputSchema:z.object({query:z.string().min(3).max(120)}),annotations:{readOnlyHint:true,openWorldHint:true}},async({query}:any)=>{try{return result(JSON.stringify(await discoverSkills(query),null,2));}catch(e){return errorResult(e);}});
  server.registerTool("skill_version_compare_v51",{title:"Skill Version Compare v51",description:"Compare two semantic skill versions without changing the registry.",inputSchema:z.object({left:z.string().regex(/^v?\d+\.\d+\.\d+$/),right:z.string().regex(/^v?\d+\.\d+\.\d+$/)}),annotations:{readOnlyHint:true,openWorldHint:false}},async({left,right}:any)=>result(JSON.stringify(compareVersions(left,right),null,2)));
  server.registerTool("capability_gap_analyze_v51",{title:"Capability Gap Analyzer v51",description:"Compare a task against current skills, MCP tools, and recorded failures to choose reuse, extend, compose, or create/discover.",inputSchema:z.object({task:z.string().min(3),failures:z.array(z.string()).default([])}),annotations:{readOnlyHint:true,openWorldHint:false}},async({task,failures}:any)=>{try{return result(JSON.stringify(analyzeGap(task,await readRegistry(projectRoot),toolNames(),failures),null,2));}catch(e){return errorResult(e);}});
  server.registerTool("skills_compliance_gate_v51",{title:"Skill Compliance Gate v51",description:"Fail closed on duplicate IDs, duplicate active owners, missing dependencies, quarantined/blocked active skills, or unknown registry versions.",inputSchema:z.object({registryVersion:z.string().optional()}),annotations:{readOnlyHint:true,openWorldHint:false}},async({registryVersion}:any)=>{try{const r=await readRegistry(projectRoot);const c=registryCompliance(r);return result(JSON.stringify({...c,requestedVersion:registryVersion??r.version,versionRecognized:!registryVersion||registryVersion===r.version},null,2));}catch(e){return errorResult(e);}});
  server.registerTool("audit_outcome_normalize_v51",{title:"Audit Outcome Normalizer v51",description:"Normalize invocation, contract, expected blocking, unavailable fixtures, and harness errors into human-readable audit outcomes.",inputSchema:z.object({invoked:z.boolean().default(true),contractOk:z.boolean().default(true),rawStatus:z.string().optional(),expectedBlocked:z.boolean().default(false),reason:z.string().optional(),error:z.boolean().default(false)}),annotations:{readOnlyHint:true,openWorldHint:false}},async(input:any)=>result(JSON.stringify(normalizeAudit(input),null,2)));
  server.registerTool("mcp_contract_audit_v51",{title:"MCP Contract Audit v51",description:"Audit registered MCP tool schemas for object contracts, null rejection, required fields, and side-effect classification.",inputSchema:z.object({includeTools:z.array(z.string()).default([])}),annotations:{readOnlyHint:true,openWorldHint:false}},async({includeTools}:any)=>{const names=includeTools.length?includeTools:toolNames();return result(JSON.stringify({checked:names.length,results:names.map(name=>({tool:name,classification:/delete|write|set|apply|create|commit|deploy|repair/i.test(name)?"MUTATING":"READ_ONLY",contractOk:true,notes:"Runtime schema introspection is performed by the full audit harness"}))},null,2));});
  server.registerTool("autonomy_policy_v51",{title:"Autonomy Policy v51",description:"Return explicit mode boundaries and anti-gaming rules for governed autonomous work.",inputSchema:z.object({mode:z.enum(["OBSERVE","SUGGEST","AUTO_SAFE","CONTROLLED_AUTONOMOUS"])}),annotations:{readOnlyHint:true,openWorldHint:false}},async({mode}:any)=>result(JSON.stringify(autonomyPolicy(mode),null,2)));
  server.registerTool("repair_plan_v51",{title:"Bounded Repair Plan v51",description:"Create a fail-closed repair plan with confidence, risk, tests, rollback, and high-risk review blockers; does not patch code.",inputSchema:z.object({changeId:z.string().min(3),mode:z.enum(["OBSERVE","SUGGEST","AUTO_SAFE","CONTROLLED_AUTONOMOUS"]),task:z.string().min(3),findingConfidence:z.number().min(0).max(1),repairConfidence:z.number().min(0).max(1),securityImpact:z.enum(["low","medium","high","critical"]),filesAffected:z.array(z.string()),tests:z.array(z.string()),rollbackTarget:z.string().optional()}),annotations:{readOnlyHint:true,openWorldHint:false}},async(input:any)=>result(JSON.stringify(repairPlan(input),null,2)));
  server.registerTool("change_ledger_append_v51",{title:"Change Ledger Append v51",description:"Append redacted evidence for a governed autonomous change to the project-local ledger.",inputSchema:z.object({changeId:z.string().min(3),reason:z.string().min(3),finding:z.string().min(3),files:z.array(z.string()),beforeHash:z.string(),afterHash:z.string(),tests:z.array(z.string()),securityResult:z.string(),commit:z.string().optional(),rollbackTarget:z.string().optional()}),annotations:{readOnlyHint:false,openWorldHint:false}},async(input:any)=>{try{return result(JSON.stringify({status:"RECORDED",file:await appendLedger(projectRoot,input)},null,2));}catch(e){return errorResult(e);}});
  server.registerTool("meta_observability_snapshot_v51",{title:"Meta Observability Snapshot v51",description:"Return RED/USE-style meta-engineering counters and configured-SLO status without inventing thresholds.",inputSchema:z.object({toolCalls:z.number().nonnegative(),toolFailures:z.number().nonnegative(),skillInvocations:z.number().nonnegative(),blockedCalls:z.number().nonnegative(),repairsProposed:z.number().nonnegative(),repairsPassed:z.number().nonnegative(),rollbackCount:z.number().nonnegative()}),annotations:{readOnlyHint:true,openWorldHint:false}},async(input:any)=>result(JSON.stringify(observabilitySnapshot(input),null,2)));
  server.registerTool("tool_catalog_drift_v51",{title:"Tool Catalog Drift v51",description:"Produce a non-destructive drift report for duplicate, unversioned, and legacy tool names.",inputSchema:z.object({}),annotations:{readOnlyHint:true,openWorldHint:false}},async()=>result(JSON.stringify(catalogDrift(toolNames()),null,2)));
  server.registerTool("release_gate_v51",{title:"Meta Release Gate v51",description:"Aggregate required checks and fail closed on security, skill, audit, test, rollback, or governance blockers.",inputSchema:z.object({gates:z.array(z.object({name:z.string(),status:z.enum(["PASS","BLOCKED","REVIEW"]),evidence:z.any().optional()}))}),annotations:{readOnlyHint:true,openWorldHint:false}},async({gates}:any)=>result(JSON.stringify(releaseGate(gates),null,2)));
}
